name: metno
description: A wrapper for the Locationforecast weather api provided by the Norwegian Meteorological Institute.
version: 1.0.0
repository: https://github.com/JHubi1/metno

environment:
  sdk: ^3.5.4

dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.13
  pubspec_generator: ^4.0.0
